version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
